server:
  port: 1111
spring:
  datasource:
    url: jdbc:mysql:///db1?useUnicode=true&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    data-password:
    data-username: root